### ISSUE TITLE
im getting errores

### ISSUE THREAD

**Issue by MARIOpremiun** [ericz99/supreme-monitor#11]
this is what I get when I'm trying to run it 
h-MacBook-Air-sl-dn:supreme-monitor-master edenichak$ yarn run start
yarn run v1.17.3
$ node index.js
internal/modules/cjs/loader.js:798
    throw err;
    ^

SyntaxError: /Users/edenichak/Desktop/supreme-monitor-master/config.json: Unexpected token . in JSON at position 350
    at JSON.parse (<anonymous>)
    at Object.Module._extensions..json (internal/modules/cjs/loader.js:795:27)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Module.require (internal/modules/cjs/loader.js:690:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (/Users/edenichak/Desktop/supreme-monitor-master/src/modules/Supreme.js:1:16)
    at Module._compile (internal/modules/cjs/loader.js:776:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:787:10)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
h-MacBook-Air-sl-dn:supreme-monitor-master edenichak$

**Comment by samoinsecure** [comment]
Bruh online shop is closed

**Comment by MARIOpremiun** [comment]
My bad btw how do I monitor all products? Or it’s only a restock monitor

**Comment by samoinsecure** [comment]
![image](https://user-images.githubusercontent.com/26344980/62853989-49542380-bcee-11e9-9303-b01cb6713ba3.png)
It's should monitor all products afaik.

**Comment by MARIOpremiun** [comment]
Ok this monitor is still working? And which format it more then 1 proxy
