### ISSUE TITLE
Getting errors

### ISSUE THREAD

**Issue by MARIOpremiun** [ericz99/supreme-monitor#13]
/Users/edenichak/Desktop/supreme-monitor/node_modules/cheerio/lib/parse.js:69
    var oldParent = node.parent || node.root,
                         ^

TypeError: Cannot read property 'parent' of null
    at Function.exports.update (/Users/edenichak/Desktop/supreme-monitor/node_modules/cheerio/lib/parse.js:69:26)
    at module.exports (/Users/edenichak/Desktop/supreme-monitor/node_modules/cheerio/lib/parse.js:19:11)
    at Function.exports.load (/Users/edenichak/Desktop/supreme-monitor/node_modules/cheerio/lib/static.js:27:14)
    at Supreme.getProductList (/Users/edenichak/Desktop/supreme-monitor/index.js:111:31)
    at Request.request [as _callback] (/Users/edenichak/Desktop/supreme-monitor/src/modules/Supreme.js:26:16)
    at Request.self.callback (/Users/edenichak/Desktop/supreme-monitor/node_modules/request/request.js:185:22)
    at Request.emit (events.js:198:13)
    at Request.<anonymous> (/Users/edenichak/Desktop/supreme-monitor/node_modules/request/request.js:1161:10)
    at Request.emit (events.js:198:13)
    at IncomingMessage.<anonymous> (/Users/edenichak/Desktop/supreme-monitor/node_modules/request/request.js:1083:12)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

This is what im getting using 10 proxies

**Comment by bushaaaa** [comment]
Same here, can't fix it
