### ISSUE TITLE
Run fine but

### ISSUE THREAD

**Issue by bigcerio** [ericz99/supreme-monitor#3]
Check all the products but after checking it
it stop and tell me:

`/root/supreme-monitor/index.js:126
                (err, { title, color, size, price }) => {
                        ^

TypeError: Cannot destructure property `title` of 'undefined' or 'null'.
    at Supreme.getProductData (/root/supremev2/index.js:126:17)
    at Request.request [as _callback] (/root/supremev2/src/modules/Supreme.js:68:16)
    at self.callback (/root/supremev2/node_modules/request/request.js:185:22)
    at emitOne (events.js:116:13)
    at Request.emit (events.js:211:7)
    at Request.onRequestError (/root/supremev2/node_modules/request/request.js:881:8)
    at emitOne (events.js:116:13)
    at ClientRequest.emit (events.js:211:7)
    at ClientRequest.onError (/root/supremev2/node_modules/tunnel-agent/index.js:179:21)
    at Object.onceWrapper (events.js:315:30)`

**Comment by ericz99** [comment]
yea.. about that it happens from time to time, just restart and it should be fine. This occurs because I didn't use endpoint instead I scrape all data from actual website, which is ideally faster. Overall, I am in process of finishing my other supreme monitor very soon.

**Comment by ericz99** [comment]
this should basically remove any sort of errors, and flexibility wise is much smoother. Hope that helps.

**Comment by bigcerio** [comment]
Ok, basically crashes every time but thats fine good project for studying...

**Comment by ericz99** [comment]
uh, it doesn't crash everytime. It just crash from time to time. Usually it won't crash at all.

**Comment by ericz99** [comment]
just wait for my other version, it won't crash at all. :)
