### ISSUE TITLE
Parent of Null Issue

### ISSUE THREAD

**Issue by CopBox** [ericz99/supreme-monitor#7]
The code is:

error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
PS C:\Users\katra\Desktop\XO\supreme-monitor-master> yarn start
yarn run v1.15.2
$ node index.js
[15:51:37.317] [Supreme Monitor V2] [+] Initial check done!
[15:51:37.323] [Supreme Monitor V2] [#] Poll Time: 2000 MS
[15:51:37.324] [Supreme Monitor V2] [#] Using 1 proxy
[15:51:37.324] [Supreme Monitor V2] [?] Running for restock!
C:\Users\katra\Desktop\XO\supreme-monitor-master\node_modules\cheerio\lib\parse.js:69
    var oldParent = node.parent || node.root,
                         ^

TypeError: Cannot read property 'parent' of null
    at Function.exports.update (C:\Users\katra\Desktop\XO\supreme-monitor-master\node_modules\cheerio\lib\parse.js:69:26)
    at module.exports (C:\Users\katra\Desktop\XO\supreme-monitor-master\node_modules\cheerio\lib\parse.js:19:11)
    at Function.exports.load (C:\Users\katra\Desktop\XO\supreme-monitor-master\node_modules\cheerio\lib\static.js:27:14)
    at Supreme.getProductList (C:\Users\katra\Desktop\XO\supreme-monitor-master\index.js:43:25)
    at Request.request [as _callback] (C:\Users\katra\Desktop\XO\supreme-monitor-master\src\modules\Supreme.js:26:16)
    at self.callback (C:\Users\katra\Desktop\XO\supreme-monitor-master\node_modules\request\request.js:185:22)
    at Request.emit (events.js:189:13)
    at Request.onRequestError (C:\Users\katra\Desktop\XO\supreme-monitor-master\node_modules\request\request.js:881:8)
    at ClientRequest.emit (events.js:189:13)
    at ClientRequest.onConnect (C:\Users\katra\Desktop\XO\supreme-monitor-master\node_modules\tunnel-agent\index.js:168:23)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
PS C:\Users\katra\Desktop\XO\supreme-monitor-master>
==========================================================
I am running US, I don't know why it is not working. If you can help me that would be grealy loved!

**Comment by ericz99** [comment]
you are probably temp ban.

**Comment by ericz99** [comment]
Closing issue, this issue only occurs when you can't parse data from supreme, and the reason behind it is because you are temp ban / ban.
